# Generated by Django 4.1.4 on 2022-12-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('hour', models.CharField(max_length=15)),
                ('credits', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=15)),
            ],
        ),
    ]
